
import React from 'react';
import { Category, Business } from './types';

export const CATEGORIES: Category[] = [
  { id: '1', name: 'Restaurantes', icon: '🍽️' },
  { id: '2', name: 'Mercados', icon: '🛒' },
  { id: '3', name: 'Serviços', icon: '🛠️' },
  { id: '4', name: 'Lojas', icon: '🛍️' },
  { id: '5', name: 'Saúde', icon: '🏥' },
  { id: '6', name: 'Educação', icon: '🎓' },
  { id: '7', name: 'Turismo', icon: '✈️' },
  { id: '8', name: 'Eventos', icon: '🎉' },
  { id: '9', name: 'Beleza', icon: '💇' },
];

export const MOCK_BUSINESSES: Business[] = [
  {
    id: 'b1',
    name: 'Pizzaria Bella Itupeva',
    ownerName: 'José Silva',
    cnpj: '12.345.678/0001-90',
    phone: '(11) 4591-1234',
    whatsapp: '5511999999999',
    email: 'bella@pizzaria.com',
    address: 'Av. Brasil, 100 - Centro, Itupeva - SP',
    category: 'Restaurantes',
    description: 'A melhor pizza no forno a lenha da cidade. Ingredientes frescos e massa artesanal.',
    imageUrl: 'https://picsum.photos/seed/pizza/800/600',
    instagram: 'pizzariabella_itupeva',
    rating: 4.8,
    status: 'APPROVED',
    isFeatured: true,
    plan: 'OURO',
    gallery: [
      'https://picsum.photos/seed/pizza1/800/600',
      'https://picsum.photos/seed/pizza2/800/600',
      'https://picsum.photos/seed/pizza3/800/600'
    ],
    createdAt: '2023-10-01',
    promotions: 'Combo Família: 2 Pizzas Grandes + Refri por R$ 89,90'
  },
  {
    id: 'b2',
    name: 'Mercado do Bairro',
    ownerName: 'Maria Oliveira',
    phone: '(11) 4591-5678',
    whatsapp: '5511988888888',
    email: 'contato@mercadobairro.com',
    address: 'Rua São Paulo, 50 - Jd. Alegria, Itupeva - SP',
    category: 'Mercados',
    description: 'Tudo o que sua família precisa com os melhores preços de Itupeva.',
    imageUrl: 'https://picsum.photos/seed/market/800/600',
    rating: 4.2,
    status: 'APPROVED',
    plan: 'BRONZE',
    createdAt: '2023-11-15'
  },
  {
    id: 'b3',
    name: 'Academia FitLife',
    ownerName: 'Ricardo Santos',
    phone: '(11) 4591-9999',
    whatsapp: '5511977777777',
    email: 'fitlife@itupeva.com',
    address: 'Rua das Flores, 200 - Centro, Itupeva - SP',
    category: 'Saúde',
    description: 'A academia mais completa de Itupeva. Musculação, Crossfit e Natação.',
    imageUrl: 'https://picsum.photos/seed/gym/800/600',
    rating: 4.9,
    status: 'APPROVED',
    isFeatured: true,
    plan: 'OURO',
    gallery: ['https://picsum.photos/seed/gym1/800/600', 'https://picsum.photos/seed/gym2/800/600'],
    createdAt: '2024-01-10'
  },
  {
    id: 'b4',
    name: 'Pet Shop Amigão',
    ownerName: 'Ana Paula',
    phone: '(11) 4591-1111',
    whatsapp: '5511966666666',
    email: 'contato@petamigao.com',
    address: 'Av. Emílio Chechinato, 500 - Itupeva - SP',
    category: 'Serviços',
    description: 'Banho e tosa com carinho. Temos rações e acessórios para seu pet.',
    imageUrl: 'https://picsum.photos/seed/pet/800/600',
    rating: 4.7,
    status: 'APPROVED',
    isFeatured: true,
    plan: 'PRATA',
    gallery: ['https://picsum.photos/seed/pet1/800/600'],
    createdAt: '2024-02-05'
  },
  {
    id: 'b5',
    name: 'Livraria Central',
    ownerName: 'Marcos Lima',
    phone: '(11) 4591-2222',
    whatsapp: '5511955555555',
    email: 'livraria@central.com',
    address: 'Rua Direita, 10 - Centro, Itupeva - SP',
    category: 'Lojas',
    description: 'O melhor acervo de livros e papelaria da região.',
    imageUrl: 'https://picsum.photos/seed/books/800/600',
    rating: 4.6,
    status: 'APPROVED',
    isFeatured: true,
    plan: 'BRONZE',
    createdAt: '2024-03-01'
  },
  {
    id: 'b6',
    name: 'Parque da Cidade Itupeva',
    ownerName: 'Prefeitura de Itupeva',
    phone: '(11) 4591-0000',
    whatsapp: '5511944444444',
    email: 'turismo@itupeva.sp.gov.br',
    address: 'Av. Emílio Chechinato, s/n - Itupeva - SP',
    category: 'Turismo',
    description: 'O principal ponto de encontro e lazer de Itupeva. Trilhas, lagos e área para piquenique.',
    imageUrl: 'https://picsum.photos/seed/park/800/600',
    rating: 4.9,
    status: 'APPROVED',
    isFeatured: true,
    plan: 'OURO',
    gallery: ['https://picsum.photos/seed/park1/800/600', 'https://picsum.photos/seed/park2/800/600'],
    createdAt: '2023-01-01'
  },
  {
    id: 'b7',
    name: 'Espaço de Eventos Itupeva',
    ownerName: 'Claudio Eventos',
    phone: '(11) 4591-3333',
    whatsapp: '5511933333333',
    email: 'contato@itupevaeventos.com',
    address: 'Rua das Palmeiras, 100 - Itupeva - SP',
    category: 'Eventos',
    description: 'O melhor espaço para seu casamento, aniversário ou evento corporativo.',
    imageUrl: 'https://picsum.photos/seed/events/800/600',
    rating: 4.8,
    status: 'APPROVED',
    isFeatured: true,
    plan: 'PRATA',
    gallery: ['https://picsum.photos/seed/events1/800/600'],
    createdAt: '2023-05-10'
  }
];
